name: DailyReport

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  schedule:
    - cron: "22 23 * * *"
    # 7:22开始执行
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
           python-version: '3.10'
      - name: 'Install requirements'
        run: pip install -r requirements.txt
      - name: 'Unzip files'
        run: |
          zipfile/zip -s 0 chrome.zip --out chrome-win.zip
          zipfile/unzip chrome-win.zip
      - name: 'Working'
        run:
          python pymain.py ${{ secrets.username }} ${{ secrets.password }}
      - name: 'Check previous status'
        if: ${{ failure() }}
        run:
          python pymain.py ${{ secrets.username }} ${{ secrets.password }}
         
